#!/usr/bin/env python3
"""Generate hotcray-diacritics.kbd — the "letter + accent key => one precomposed
character" logic for kanata.

Why generated: every (letter, accent) pair that exists as a single Unicode
character needs its own rule; there are ~250 of them. Writing them by hand
would be error-prone, so this script asks Python's unicodedata which pairs
compose (NFC) and writes the kanata rules.

Run from the repository root after changing ACCENTS below:
    python3 tools/gen_diacritics.py
"""
import unicodedata
from pathlib import Path

# alias name -> (combining character, description). The physical keys are
# assigned in hotcray.kbd (AltGr+Shift layer), not here.
ACCENTS = {
    "dia-grave":      ("̀", "grave         à"),
    "dia-acute":      ("́", "acute         á"),
    "dia-circumflex": ("̂", "circumflex    â"),
    "dia-tilde":      ("̃", "tilde         ã"),
    "dia-macron":     ("̄", "macron        ā"),
    "dia-diaeresis":  ("̈", "diaeresis     ä"),
    "dia-ring":       ("̊", "ring above    å"),
    "dia-dblacute":   ("̋", "double acute  ő"),
    "dia-caron":      ("̌", "caron         ǎ"),
    "dia-cedilla":    ("̧", "cedilla       ç"),
    "dia-ogonek":     ("̨", "ogonek        ą"),
}

# How recently (ms) the letter must have been typed for the accent to merge
# with it. Protects against deleting a character in some other text field
# after you clicked elsewhere with the mouse (kanata cannot see mouse clicks).
MAX_AGE_MS = 3000

HEADER = f""";; ============================================================================
;;  hotcray-diacritics.kbd  —  GENERATED by tools/gen_diacritics.py. Do not
;;  edit by hand: change the script and re-run it.
;; ============================================================================
;;
;;  What this does
;;  --------------
;;  You type a letter, then an accent key (AltGr+Shift+...), exactly like with
;;  the old Hotcray. Old Hotcray then inserted an invisible "combining" accent
;;  character after the letter (e + U+0301), which many search bars, file
;;  names and spell checkers treat as two characters.
;;
;;  Now kanata looks at the last keys it typed ("key-history"):
;;    * if the previous key was a Latin letter typed less than {MAX_AGE_MS} ms ago and
;;      Unicode has a single precomposed character for letter+accent, kanata
;;      sends Backspace and then that character (é, Ś, ǎ, ...);
;;    * otherwise it falls back to the old behaviour: it types the combining
;;      accent itself (useful for exotic combinations like q̃).
;;
;;  Upper case is detected through the invisible marker key `nop1`, which the
;;  Latin layer "presses" together with every shifted letter (nop keys are
;;  never sent to the OS; they only exist inside kanata's history).
;;
;;  Merging only happens while the Latin base layer is active. In the Cyrillic
;;  layer the accent keys always type the combining character.
;;
;;  The patterns below account for the Shift press that is part of the
;;  AltGr+Shift accent chord itself: that Shift press may sit between the
;;  letter and the accent in the history (slot 1), or not (if Shift was
;;  already held while typing the letter).
"""


def compositions(mark):
    for ch in "abcdefghijklmnopqrstuvwxyz":
        lo = unicodedata.normalize("NFC", ch + mark)
        up = unicodedata.normalize("NFC", ch.upper() + mark)
        yield ch, (lo if len(lo) == 1 else None), (up if len(up) == 1 else None)


def rule(letter, upper):
    # Returns the kanata logic list that matches "previous letter = <letter>"
    # in the requested case, considering the possible Shift press in between.
    t = f"(key-timing {{n}} lt {MAX_AGE_MS})"
    if upper:
        pats = [
            f"(and (key-history nop1 1) (key-history {letter} 2) {t.format(n=2)})",
            f"(and (key-history lsft 1) (key-history nop1 2) (key-history {letter} 3) {t.format(n=3)})",
            f"(and (key-history rsft 1) (key-history nop1 2) (key-history {letter} 3) {t.format(n=3)})",
        ]
    else:
        pats = [
            f"(and (key-history {letter} 1) {t.format(n=1)})",
            f"(and (key-history lsft 1) (key-history {letter} 2) {t.format(n=2)})",
            f"(and (key-history rsft 1) (key-history {letter} 2) {t.format(n=2)})",
        ]
    return "(and (base-layer lat) (or " + " ".join(pats) + "))"


def main():
    out = [HEADER, "(defalias"]
    total = 0
    for alias, (mark, desc) in ACCENTS.items():
        out.append(f"\n  ;; ---- {desc} ----")
        out.append(f"  {alias} (switch")
        for letter, lo, up in compositions(mark):
            # Upper-case rules must come first: an upper-case letter also
            # matches the lower-case patterns' shape one slot later.
            if up:
                out.append(f"    ({rule(letter, True)}) (macro bspc (unicode {up})) break")
                total += 1
            if lo:
                out.append(f"    ({rule(letter, False)}) (macro bspc (unicode {lo})) break")
                total += 1
        cp = f"U+{ord(mark):04X}"
        out.append(f"    () (unicode {cp}) break)")
    out.append(")\n")
    path = Path(__file__).resolve().parent.parent / "hotcray-diacritics.kbd"
    path.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {path} ({total} precomposed characters)")


if __name__ == "__main__":
    main()
